linters:
  enable:
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unused
    - errcheck
    - ineffassign
    - containedctx
    - tenv
    - musttag
    - mirror
    - tagalign
    - zerologlint
    - copyloopvar
    - gosec
    - misspell
    - noctx
    - prealloc
    - protogetter
    - makezero
linters-settings:
  gosec:
    excludes:
      - G115