version: "2"
linters:
  enable:
    - containedctx
    - copyloopvar
    - goconst
    - gocritic
    - gosec
    - makezero
    - mirror
    - misspell
    - musttag
    - noctx
    - prealloc
    - protogetter
    - tagalign
    - unconvert
    - usetesting
    - zerologlint
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
