// SPDX-FileCopyrightText: 2025 Bb Strategy Pte. Ltd. <celenium@baking-bad.org>
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: forwarding.go
//
// Generated by this command:
//
//	mockgen -source=forwarding.go -destination=mock/forwarding.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/celenium-io/celestia-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIForwarding is a mock of IForwarding interface.
type MockIForwarding struct {
	ctrl     *gomock.Controller
	recorder *MockIForwardingMockRecorder
	isgomock struct{}
}

// MockIForwardingMockRecorder is the mock recorder for MockIForwarding.
type MockIForwardingMockRecorder struct {
	mock *MockIForwarding
}

// NewMockIForwarding creates a new mock instance.
func NewMockIForwarding(ctrl *gomock.Controller) *MockIForwarding {
	mock := &MockIForwarding{ctrl: ctrl}
	mock.recorder = &MockIForwardingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIForwarding) EXPECT() *MockIForwardingMockRecorder {
	return m.recorder
}

// ById mocks base method.
func (m *MockIForwarding) ById(ctx context.Context, id uint64) (storage.Forwarding, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ById", ctx, id)
	ret0, _ := ret[0].(storage.Forwarding)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ById indicates an expected call of ById.
func (mr *MockIForwardingMockRecorder) ById(ctx, id any) *MockIForwardingByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ById", reflect.TypeOf((*MockIForwarding)(nil).ById), ctx, id)
	return &MockIForwardingByIdCall{Call: call}
}

// MockIForwardingByIdCall wrap *gomock.Call
type MockIForwardingByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingByIdCall) Return(arg0 storage.Forwarding, arg1 time.Time, arg2 error) *MockIForwardingByIdCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingByIdCall) Do(f func(context.Context, uint64) (storage.Forwarding, time.Time, error)) *MockIForwardingByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingByIdCall) DoAndReturn(f func(context.Context, uint64) (storage.Forwarding, time.Time, error)) *MockIForwardingByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIForwarding) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Forwarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Forwarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIForwardingMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIForwardingCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIForwarding)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIForwardingCursorListCall{Call: call}
}

// MockIForwardingCursorListCall wrap *gomock.Call
type MockIForwardingCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingCursorListCall) Return(arg0 []*storage.Forwarding, arg1 error) *MockIForwardingCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Forwarding, error)) *MockIForwardingCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Forwarding, error)) *MockIForwardingCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Filter mocks base method.
func (m *MockIForwarding) Filter(ctx context.Context, filters storage.ForwardingFilter) ([]storage.Forwarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, filters)
	ret0, _ := ret[0].([]storage.Forwarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockIForwardingMockRecorder) Filter(ctx, filters any) *MockIForwardingFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockIForwarding)(nil).Filter), ctx, filters)
	return &MockIForwardingFilterCall{Call: call}
}

// MockIForwardingFilterCall wrap *gomock.Call
type MockIForwardingFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingFilterCall) Return(arg0 []storage.Forwarding, arg1 error) *MockIForwardingFilterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingFilterCall) Do(f func(context.Context, storage.ForwardingFilter) ([]storage.Forwarding, error)) *MockIForwardingFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingFilterCall) DoAndReturn(f func(context.Context, storage.ForwardingFilter) ([]storage.Forwarding, error)) *MockIForwardingFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIForwarding) GetByID(ctx context.Context, id uint64) (*storage.Forwarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Forwarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIForwardingMockRecorder) GetByID(ctx, id any) *MockIForwardingGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIForwarding)(nil).GetByID), ctx, id)
	return &MockIForwardingGetByIDCall{Call: call}
}

// MockIForwardingGetByIDCall wrap *gomock.Call
type MockIForwardingGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingGetByIDCall) Return(arg0 *storage.Forwarding, arg1 error) *MockIForwardingGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingGetByIDCall) Do(f func(context.Context, uint64) (*storage.Forwarding, error)) *MockIForwardingGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Forwarding, error)) *MockIForwardingGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Inputs mocks base method.
func (m *MockIForwarding) Inputs(ctx context.Context, addressId uint64, from, to time.Time) ([]storage.ForwardingInput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inputs", ctx, addressId, from, to)
	ret0, _ := ret[0].([]storage.ForwardingInput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inputs indicates an expected call of Inputs.
func (mr *MockIForwardingMockRecorder) Inputs(ctx, addressId, from, to any) *MockIForwardingInputsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inputs", reflect.TypeOf((*MockIForwarding)(nil).Inputs), ctx, addressId, from, to)
	return &MockIForwardingInputsCall{Call: call}
}

// MockIForwardingInputsCall wrap *gomock.Call
type MockIForwardingInputsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingInputsCall) Return(arg0 []storage.ForwardingInput, arg1 error) *MockIForwardingInputsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingInputsCall) Do(f func(context.Context, uint64, time.Time, time.Time) ([]storage.ForwardingInput, error)) *MockIForwardingInputsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingInputsCall) DoAndReturn(f func(context.Context, uint64, time.Time, time.Time) ([]storage.ForwardingInput, error)) *MockIForwardingInputsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIForwarding) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIForwardingMockRecorder) IsNoRows(err any) *MockIForwardingIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIForwarding)(nil).IsNoRows), err)
	return &MockIForwardingIsNoRowsCall{Call: call}
}

// MockIForwardingIsNoRowsCall wrap *gomock.Call
type MockIForwardingIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingIsNoRowsCall) Return(arg0 bool) *MockIForwardingIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingIsNoRowsCall) Do(f func(error) bool) *MockIForwardingIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIForwardingIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIForwarding) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIForwardingMockRecorder) LastID(ctx any) *MockIForwardingLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIForwarding)(nil).LastID), ctx)
	return &MockIForwardingLastIDCall{Call: call}
}

// MockIForwardingLastIDCall wrap *gomock.Call
type MockIForwardingLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingLastIDCall) Return(arg0 uint64, arg1 error) *MockIForwardingLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIForwardingLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIForwardingLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIForwarding) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Forwarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Forwarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIForwardingMockRecorder) List(ctx, limit, offset, order any) *MockIForwardingListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIForwarding)(nil).List), ctx, limit, offset, order)
	return &MockIForwardingListCall{Call: call}
}

// MockIForwardingListCall wrap *gomock.Call
type MockIForwardingListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingListCall) Return(arg0 []*storage.Forwarding, arg1 error) *MockIForwardingListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Forwarding, error)) *MockIForwardingListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Forwarding, error)) *MockIForwardingListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIForwarding) Save(ctx context.Context, m *storage.Forwarding) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIForwardingMockRecorder) Save(ctx, m any) *MockIForwardingSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIForwarding)(nil).Save), ctx, m)
	return &MockIForwardingSaveCall{Call: call}
}

// MockIForwardingSaveCall wrap *gomock.Call
type MockIForwardingSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingSaveCall) Return(arg0 error) *MockIForwardingSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingSaveCall) Do(f func(context.Context, *storage.Forwarding) error) *MockIForwardingSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingSaveCall) DoAndReturn(f func(context.Context, *storage.Forwarding) error) *MockIForwardingSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIForwarding) Update(ctx context.Context, m *storage.Forwarding) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIForwardingMockRecorder) Update(ctx, m any) *MockIForwardingUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIForwarding)(nil).Update), ctx, m)
	return &MockIForwardingUpdateCall{Call: call}
}

// MockIForwardingUpdateCall wrap *gomock.Call
type MockIForwardingUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIForwardingUpdateCall) Return(arg0 error) *MockIForwardingUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIForwardingUpdateCall) Do(f func(context.Context, *storage.Forwarding) error) *MockIForwardingUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIForwardingUpdateCall) DoAndReturn(f func(context.Context, *storage.Forwarding) error) *MockIForwardingUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
