// SPDX-FileCopyrightText: 2025 Bb Strategy Pte. Ltd. <celenium@baking-bad.org>
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: vesting_account.go
//
// Generated by this command:
//
//	mockgen -source=vesting_account.go -destination=mock/vesting_account.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/celenium-io/celestia-indexer/internal/storage"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIVestingAccount is a mock of IVestingAccount interface.
type MockIVestingAccount struct {
	ctrl     *gomock.Controller
	recorder *MockIVestingAccountMockRecorder
}

// MockIVestingAccountMockRecorder is the mock recorder for MockIVestingAccount.
type MockIVestingAccountMockRecorder struct {
	mock *MockIVestingAccount
}

// NewMockIVestingAccount creates a new mock instance.
func NewMockIVestingAccount(ctrl *gomock.Controller) *MockIVestingAccount {
	mock := &MockIVestingAccount{ctrl: ctrl}
	mock.recorder = &MockIVestingAccountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVestingAccount) EXPECT() *MockIVestingAccountMockRecorder {
	return m.recorder
}

// ByAddress mocks base method.
func (m *MockIVestingAccount) ByAddress(ctx context.Context, addressId uint64, limit, offset int, showEnded bool) ([]storage.VestingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByAddress", ctx, addressId, limit, offset, showEnded)
	ret0, _ := ret[0].([]storage.VestingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByAddress indicates an expected call of ByAddress.
func (mr *MockIVestingAccountMockRecorder) ByAddress(ctx, addressId, limit, offset, showEnded any) *MockIVestingAccountByAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByAddress", reflect.TypeOf((*MockIVestingAccount)(nil).ByAddress), ctx, addressId, limit, offset, showEnded)
	return &MockIVestingAccountByAddressCall{Call: call}
}

// MockIVestingAccountByAddressCall wrap *gomock.Call
type MockIVestingAccountByAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountByAddressCall) Return(arg0 []storage.VestingAccount, arg1 error) *MockIVestingAccountByAddressCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountByAddressCall) Do(f func(context.Context, uint64, int, int, bool) ([]storage.VestingAccount, error)) *MockIVestingAccountByAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountByAddressCall) DoAndReturn(f func(context.Context, uint64, int, int, bool) ([]storage.VestingAccount, error)) *MockIVestingAccountByAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIVestingAccount) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.VestingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.VestingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIVestingAccountMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIVestingAccountCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIVestingAccount)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIVestingAccountCursorListCall{Call: call}
}

// MockIVestingAccountCursorListCall wrap *gomock.Call
type MockIVestingAccountCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountCursorListCall) Return(arg0 []*storage.VestingAccount, arg1 error) *MockIVestingAccountCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VestingAccount, error)) *MockIVestingAccountCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.VestingAccount, error)) *MockIVestingAccountCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIVestingAccount) GetByID(ctx context.Context, id uint64) (*storage.VestingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.VestingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIVestingAccountMockRecorder) GetByID(ctx, id any) *MockIVestingAccountGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIVestingAccount)(nil).GetByID), ctx, id)
	return &MockIVestingAccountGetByIDCall{Call: call}
}

// MockIVestingAccountGetByIDCall wrap *gomock.Call
type MockIVestingAccountGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountGetByIDCall) Return(arg0 *storage.VestingAccount, arg1 error) *MockIVestingAccountGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountGetByIDCall) Do(f func(context.Context, uint64) (*storage.VestingAccount, error)) *MockIVestingAccountGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.VestingAccount, error)) *MockIVestingAccountGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIVestingAccount) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIVestingAccountMockRecorder) IsNoRows(err any) *MockIVestingAccountIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIVestingAccount)(nil).IsNoRows), err)
	return &MockIVestingAccountIsNoRowsCall{Call: call}
}

// MockIVestingAccountIsNoRowsCall wrap *gomock.Call
type MockIVestingAccountIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountIsNoRowsCall) Return(arg0 bool) *MockIVestingAccountIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountIsNoRowsCall) Do(f func(error) bool) *MockIVestingAccountIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIVestingAccountIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIVestingAccount) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIVestingAccountMockRecorder) LastID(ctx any) *MockIVestingAccountLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIVestingAccount)(nil).LastID), ctx)
	return &MockIVestingAccountLastIDCall{Call: call}
}

// MockIVestingAccountLastIDCall wrap *gomock.Call
type MockIVestingAccountLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountLastIDCall) Return(arg0 uint64, arg1 error) *MockIVestingAccountLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIVestingAccountLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIVestingAccountLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIVestingAccount) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.VestingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.VestingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIVestingAccountMockRecorder) List(ctx, limit, offset, order any) *MockIVestingAccountListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIVestingAccount)(nil).List), ctx, limit, offset, order)
	return &MockIVestingAccountListCall{Call: call}
}

// MockIVestingAccountListCall wrap *gomock.Call
type MockIVestingAccountListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountListCall) Return(arg0 []*storage.VestingAccount, arg1 error) *MockIVestingAccountListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VestingAccount, error)) *MockIVestingAccountListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.VestingAccount, error)) *MockIVestingAccountListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIVestingAccount) Save(ctx context.Context, m *storage.VestingAccount) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIVestingAccountMockRecorder) Save(ctx, m any) *MockIVestingAccountSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIVestingAccount)(nil).Save), ctx, m)
	return &MockIVestingAccountSaveCall{Call: call}
}

// MockIVestingAccountSaveCall wrap *gomock.Call
type MockIVestingAccountSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountSaveCall) Return(arg0 error) *MockIVestingAccountSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountSaveCall) Do(f func(context.Context, *storage.VestingAccount) error) *MockIVestingAccountSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountSaveCall) DoAndReturn(f func(context.Context, *storage.VestingAccount) error) *MockIVestingAccountSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIVestingAccount) Update(ctx context.Context, m *storage.VestingAccount) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIVestingAccountMockRecorder) Update(ctx, m any) *MockIVestingAccountUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIVestingAccount)(nil).Update), ctx, m)
	return &MockIVestingAccountUpdateCall{Call: call}
}

// MockIVestingAccountUpdateCall wrap *gomock.Call
type MockIVestingAccountUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIVestingAccountUpdateCall) Return(arg0 error) *MockIVestingAccountUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIVestingAccountUpdateCall) Do(f func(context.Context, *storage.VestingAccount) error) *MockIVestingAccountUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIVestingAccountUpdateCall) DoAndReturn(f func(context.Context, *storage.VestingAccount) error) *MockIVestingAccountUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
