// SPDX-FileCopyrightText: 2024 PK Lab AG <contact@pklab.io>
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock.go -package=blob -typed
//
// Package blob is a generated GoMock package.
package blob

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Head mocks base method.
func (m *MockStorage) Head(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockStorageMockRecorder) Head(ctx any) *StorageHeadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockStorage)(nil).Head), ctx)
	return &StorageHeadCall{Call: call}
}

// StorageHeadCall wrap *gomock.Call
type StorageHeadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StorageHeadCall) Return(arg0 uint64, arg1 error) *StorageHeadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StorageHeadCall) Do(f func(context.Context) (uint64, error)) *StorageHeadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StorageHeadCall) DoAndReturn(f func(context.Context) (uint64, error)) *StorageHeadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockStorage) Save(ctx context.Context, blob Blob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, blob)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorageMockRecorder) Save(ctx, blob any) *StorageSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorage)(nil).Save), ctx, blob)
	return &StorageSaveCall{Call: call}
}

// StorageSaveCall wrap *gomock.Call
type StorageSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StorageSaveCall) Return(arg0 error) *StorageSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StorageSaveCall) Do(f func(context.Context, Blob) error) *StorageSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StorageSaveCall) DoAndReturn(f func(context.Context, Blob) error) *StorageSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveBulk mocks base method.
func (m *MockStorage) SaveBulk(ctx context.Context, blobs []Blob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBulk", ctx, blobs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBulk indicates an expected call of SaveBulk.
func (mr *MockStorageMockRecorder) SaveBulk(ctx, blobs any) *StorageSaveBulkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBulk", reflect.TypeOf((*MockStorage)(nil).SaveBulk), ctx, blobs)
	return &StorageSaveBulkCall{Call: call}
}

// StorageSaveBulkCall wrap *gomock.Call
type StorageSaveBulkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StorageSaveBulkCall) Return(arg0 error) *StorageSaveBulkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StorageSaveBulkCall) Do(f func(context.Context, []Blob) error) *StorageSaveBulkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StorageSaveBulkCall) DoAndReturn(f func(context.Context, []Blob) error) *StorageSaveBulkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateHead mocks base method.
func (m *MockStorage) UpdateHead(ctx context.Context, head uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHead", ctx, head)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHead indicates an expected call of UpdateHead.
func (mr *MockStorageMockRecorder) UpdateHead(ctx, head any) *StorageUpdateHeadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHead", reflect.TypeOf((*MockStorage)(nil).UpdateHead), ctx, head)
	return &StorageUpdateHeadCall{Call: call}
}

// StorageUpdateHeadCall wrap *gomock.Call
type StorageUpdateHeadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *StorageUpdateHeadCall) Return(arg0 error) *StorageUpdateHeadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *StorageUpdateHeadCall) Do(f func(context.Context, uint64) error) *StorageUpdateHeadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *StorageUpdateHeadCall) DoAndReturn(f func(context.Context, uint64) error) *StorageUpdateHeadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
