name: Pre-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Publish GitHub release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
          SENTRY_URL: "${{ secrets.SENTRY_URL }}"
        with:
          environment: production
