name: Pre-release
permissions:
  contents: write
  pull-requests: read
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Publish GitHub release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          generate_release_notes: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

  sentry:
    name: Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Create Sentry release
        uses: getsentry/action-release@a74facf8a080ecbdf1cb355f16743530d712abb7 # v1.11.0
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
          SENTRY_URL: "${{ secrets.SENTRY_URL }}"
        with:
          environment: production
          version: "${{ github.ref_name }}"
          ignore_empty: true
