name: Release
permissions:
  contents: write
  pull-requests: read
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Publish GitHub release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  sentry:
    name: Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create Sentry release
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
          SENTRY_URL: "${{ secrets.SENTRY_URL }}"
        with:
          environment: production
          version: "${{ github.ref_name }}"
          ignore_empty: true
