name: Release
permissions:
  contents: write
  pull-requests: read
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Publish GitHub release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  sentry:
    name: Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Create Sentry release
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
          SENTRY_URL: "${{ secrets.SENTRY_URL }}"
        with:
          environment: production
          version: "${{ github.ref_name }}"
          ignore_empty: true
