on:
  push:

name: Tests
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '1.26'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.11.3
          args: --timeout=5m
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: 1.26.x

      - name: Golang tests
        env:
          GO111MODULE: on
        run: |
          go mod download
          go test -p 8 ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@6a57a39604c9f4682dc9c37a21e78fb3a234b8f4 # v0.2.5
        with:
          report: 'true'
          chart: 'true'
          amend: 'true'
          reuse-go: 'true'
        continue-on-error: true
